version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  pgvector:
    image: ankane/pgvector:latest
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_DB: newsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mysql:
    image: mysql:8.1
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ghbdtn!234
      MYSQL_DATABASE: newsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  redis_data:
  pgdata:
  mysqldata:
