"""add has_summary to news table

Revision ID: 1a681d80a4b9
Revises: 4a831fdc6ece
Create Date: 2025-08-20 09:51:40.980705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a681d80a4b9'
down_revision: Union[str, Sequence[str], None] = '4a831fdc6ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('has_summary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'has_summary')
    # ### end Alembic commands ###
