"""add titles and summaries fields to news table

Revision ID: 4a831fdc6ece
Revises: 8067b4ad7aee
Create Date: 2025-08-19 16:43:35.614593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a831fdc6ece'
down_revision: Union[str, Sequence[str], None] = '8067b4ad7aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('title_ru', sa.String(length=255), nullable=True))
    op.add_column('news', sa.Column('title_kz', sa.String(length=255), nullable=True))
    op.add_column('news', sa.Column('title_en', sa.String(length=255), nullable=True))
    op.add_column('news', sa.Column('summary_ru', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('summary_kz', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('summary_en', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'summary_en')
    op.drop_column('news', 'summary_kz')
    op.drop_column('news', 'summary_ru')
    op.drop_column('news', 'title_en')
    op.drop_column('news', 'title_kz')
    op.drop_column('news', 'title_ru')
    # ### end Alembic commands ###
